"""Initial migration

Revision ID: cfe2217d4ddf
Revises: 
Create Date: 2024-06-17 14:12:51.968138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe2217d4ddf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('energia_contratada2', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_data', schema=None) as batch_op:
        batch_op.drop_column('energia_contratada2')

    # ### end Alembic commands ###
